apiVersion: apps/v1
kind: Deployment
metadata:
  name: relidrabbitmq-230203
  namespace: relid-23-02-03
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      #hostAliases:
      #  - hostnames:
      #    - "relidmongodb01"
      #    ip: "10.0.74.12"
      volumes:
      - name: rabbitmq-certs230203
        persistentVolumeClaim:
          claimName: relidmqcerts230203-pvc
      containers:
      - name: relidrabbitmq
        image: relidacr.azurecr.io/23.02.03:rabbitmq-2909
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
        - containerPort: 5671
        volumeMounts:
            - mountPath: /ssl-certs
              name: rabbcerts-vol
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: relid-23-02-03
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5671
      targetPort: 5671
